"""Regression coverage for the Tom Kim Presidents Cup record article.

The page is generated by scripts/publish_tom_kim_presidents_cup.py from
article-template.html and registered in articles.json; sync_site.py then
places it on the homepage, news, the PGA Tour hub, search, the feed and both
sitemaps. These checks pin what a reader and a crawler get.
"""

import json
import re
import unittest
from html.parser import HTMLParser
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SLUG = "tom-kim-presidents-cup-record-medinah"
CANONICAL = f"https://www.golfraw.com/{SLUG}"
IMAGE = "/public/tom-kim-presidents-cup-medinah.webp"
TITLE = "Tom Kim Presidents Cup Record: 3-5-1 and a Rematch Waiting"
H1 = "Tom Kim Is 3-5-1 at the Presidents Cup. The Villain Label Doesn't Fit the Record."
DESCRIPTION = (
    "What Tom Kim said in 2024, what he walked back, his 3-5-1 Presidents Cup record, "
    "and why the Schauffele-Cantlay rematch at Medinah matters more than the boos."
)


class JsonLdParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.blocks = []
        self._capturing = False
        self._buffer = []

    def handle_starttag(self, tag, attrs):
        if tag == "script" and dict(attrs).get("type") == "application/ld+json":
            self._capturing = True
            self._buffer = []

    def handle_data(self, data):
        if self._capturing:
            self._buffer.append(data)

    def handle_endtag(self, tag):
        if tag == "script" and self._capturing:
            self.blocks.append("".join(self._buffer))
            self._capturing = False


def objects(value):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from objects(child)
    elif isinstance(value, list):
        for child in value:
            yield from objects(child)


class TomKimArticleTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.path = ROOT / f"{SLUG}.html"
        cls.html = cls.path.read_text(encoding="utf-8") if cls.path.exists() else ""
        cls.registry = json.loads((ROOT / "articles.json").read_text(encoding="utf-8"))

    def test_page_and_hero_exist(self):
        self.assertTrue(self.path.exists())
        asset = ROOT / IMAGE.lstrip("/")
        self.assertTrue(asset.exists(), "the hero is uploaded by hand to public/")
        self.assertEqual(b"RIFF", asset.read_bytes()[:4])
        self.assertEqual(b"WEBP", asset.read_bytes()[8:12])

    def test_registry_entry_routes_to_the_pga_tour_hub(self):
        record = next(r for r in self.registry["articles"] if r.get("slug") == SLUG)
        self.assertEqual(f"/{SLUG}", record["url"])
        self.assertEqual(f"/{SLUG}", record["canonical"])
        self.assertEqual(IMAGE, record["image"])
        self.assertEqual("2026-09-23", record["date"])
        self.assertEqual(["PGA TOUR", "PRESIDENTS CUP", "PRO GOLF"], record["category"])
        self.assertEqual("PGA TOUR", record["section"])
        self.assertIn("Tom Kim Presidents Cup record", record["keywords"])

    def test_head_metadata_is_page_specific(self):
        self.assertIn(f"<title>{TITLE}</title>", self.html)
        self.assertIn(f'<meta name="description" content="{DESCRIPTION}">', self.html)
        self.assertIn(f'<link rel="canonical" href="{CANONICAL}">', self.html)
        self.assertIn(f'<meta property="og:url" content="{CANONICAL}">', self.html)
        self.assertIn(f'<meta property="og:image" content="https://www.golfraw.com{IMAGE}">', self.html)
        self.assertIn('<meta property="og:image:width" content="1536">', self.html)
        self.assertIn('<meta property="og:image:height" content="1024">', self.html)
        self.assertIn('<meta property="article:published_time" content="2026-09-23T16:45:00+02:00"', self.html)
        self.assertIn('<meta property="article:section" content="PGA Tour">', self.html)
        self.assertEqual(1, self.html.count("<h1"))
        self.assertIn(f"<h1>{H1.replace(chr(39), '&#x27;')}</h1>", self.html)
        # nothing from the Oakmont scaffold survives
        for leftover in ("Oakmont", 'href="#"', "#ratings", "M. KEANE"):
            self.assertNotIn(leftover, self.html, leftover)

    def test_hero_carries_its_real_dimensions(self):
        tag = re.search(rf'<img src="{re.escape(IMAGE)}"[^>]*>', self.html).group(0)
        for attr in ('alt="Tom Kim of the International Team during a Presidents Cup match"',
                     'width="1536"', 'height="1024"', 'fetchpriority="high"', 'loading="eager"'):
            self.assertIn(attr, tag, attr)

    def test_record_table_and_internal_links(self):
        self.assertIn('<caption class="sr-only">Tom Kim\'s Presidents Cup record by year</caption>', self.html)
        for cell in ("Quail Hollow", "2-3-0", "Royal Montreal", "1-2-1", "3-5-1", "0 team wins"):
            self.assertIn(f"<td>{cell}</td>", self.html, cell)
        # the two anchors in the brief resolve to pages that exist
        for href in ("/presidents-cup-captain-liv-golf-restrictions-international-team", "/solheim-cup-prize-money-ryder-cup-500k"):
            self.assertIn(f'href="{href}"', self.html)
            self.assertTrue((ROOT / (href.lstrip("/") + ".html")).exists(), href)
        for dead in ("/presidents-cup-format-explained", "/solheim-cup-prize-money-players-paid"):
            self.assertNotIn(dead, self.html, dead)

    def test_verified_figures_are_present(self):
        for value in ("3 wins, 5 losses and 1 half", "18.5&ndash;11.5", "17.5&ndash;12.5", "4-1-0",
                      "12 July 2026", "1,010 days", "13 of the previous 15", "15.5 wins the cup"):
            self.assertIn(value, self.html, value)

    def test_json_ld_is_a_news_article_with_publisher_and_breadcrumb(self):
        parser = JsonLdParser()
        parser.feed(self.html)
        documents = [json.loads(block) for block in parser.blocks]
        nodes = [item for document in documents for item in objects(document)]
        types = {item.get("@type") for item in nodes}
        self.assertTrue({"NewsArticle", "Organization", "BreadcrumbList"} <= types, types)
        article = next(item for item in nodes if item.get("@type") == "NewsArticle")
        # scripts/article_schema.py keeps the headline aligned with the page
        # title when the two describe the same story, as on every article
        self.assertEqual(TITLE, article["headline"])
        self.assertEqual(CANONICAL, article["mainEntityOfPage"])
        self.assertEqual("2026-09-23T16:45:00+02:00", article["datePublished"])
        self.assertEqual("GolfRaw Editorial", article["author"]["name"])
        self.assertEqual("https://www.golfraw.com#organization", article["publisher"]["@id"])
        image = article["image"]
        image_url = image["url"] if isinstance(image, dict) else image[0]
        self.assertEqual(f"https://www.golfraw.com{IMAGE}", image_url)
        org = next(item for item in nodes if item.get("@type") == "Organization" and item.get("name") == "GolfRaw")
        self.assertEqual("https://www.golfraw.com/icon-512.png", org["logo"]["url"])

    def test_synced_surfaces_carry_the_article(self):
        for name in ("index.html", "news.html", "pga-tour.html", "search.html", "feed.xml"):
            with self.subTest(name):
                self.assertIn(f"/{SLUG}", (ROOT / name).read_text(encoding="utf-8"))
        sitemap = (ROOT / "sitemap.xml").read_text(encoding="utf-8")
        self.assertIn(f"<loc>{CANONICAL}</loc>\n    <lastmod>2026-09-23</lastmod>", sitemap)
        self.assertIn(f"<loc>{CANONICAL}</loc>", (ROOT / "news-sitemap.xml").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
