"""Regression coverage for the "3 clubs that feel like a cheat code" guide.

Generated by scripts/publish_cheat_code_clubs.py from article-template.html,
registered in articles.json, and placed on the homepage, guides hub, search,
feed and sitemap by sync_site.py. The visible FAQ and the FAQPage node come
from one list, and this pins that they still match.
"""

import json
import re
import unittest
from pathlib import Path

from scripts.schema_normalizer import extract_visible_faq


ROOT = Path(__file__).resolve().parents[1]
SLUG = "clubs-that-feel-like-a-cheat-code"
CANONICAL = f"https://www.golfraw.com/{SLUG}"
IMAGE = "/public/clubs-that-feel-like-a-cheat-code.webp"
TITLE = "3 Clubs That Feel Like a Cheat Code (the Data Backs 2) | GolfRaw"
H1 = "3 Clubs That Feel Like a Cheat Code on the Course"
DESCRIPTION = (
    "A 7-wood, a hybrid and a chipper. Tracking data from millions of amateur rounds "
    "shows two of them lower scores. The third comes with a catch."
)
JSON_LD = re.compile(r'<script type="application/ld\+json">(.*?)</script>', re.S)


def nodes(source):
    out = []
    for block in JSON_LD.findall(source):
        document = json.loads(block)
        out.extend(document.get("@graph") or [document])
    return out


class CheatCodeClubsTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.html = (ROOT / f"{SLUG}.html").read_text(encoding="utf-8")
        cls.registry = json.loads((ROOT / "articles.json").read_text(encoding="utf-8"))

    def test_registry_entry_is_a_guide(self):
        record = next(r for r in self.registry["articles"] if r.get("slug") == SLUG)
        self.assertEqual(f"/{SLUG}", record["url"])
        self.assertEqual(f"/{SLUG}", record["canonical"])
        self.assertEqual(IMAGE, record["image"])
        self.assertEqual("2026-09-24", record["date"])
        self.assertEqual("GUIDES", record["section"])
        self.assertEqual("GUIDES", record["category"][0])
        self.assertEqual("7 min read", record["reading_time"])

    def test_head_metadata_is_page_specific(self):
        self.assertIn(f"<title>{TITLE}</title>", self.html)
        self.assertIn(f'<meta name="description" content="{DESCRIPTION}">', self.html)
        self.assertIn(f'<link rel="canonical" href="{CANONICAL}">', self.html)
        self.assertIn(f'<meta property="og:url" content="{CANONICAL}">', self.html)
        self.assertIn(f'<meta property="og:image" content="https://www.golfraw.com{IMAGE}">', self.html)
        self.assertIn('<meta property="article:published_time" content="2026-09-24T15:55:00+02:00"', self.html)
        self.assertIn('<meta property="article:section" content="Guides">', self.html)
        self.assertEqual(1, self.html.count("<h1"))
        self.assertIn(f"<h1>{H1}</h1>", self.html)
        for leftover in ("Oakmont", 'href="#"', "#ratings", "M. KEANE"):
            self.assertNotIn(leftover, self.html, leftover)

    def test_hero_alt_and_path(self):
        tag = re.search(rf'<img src="{re.escape(IMAGE)}"[^>]*>', self.html).group(0)
        self.assertIn('alt="The three golf clubs that feel like a cheat code: 7-wood, hybrid and chipper"', tag)
        self.assertIn('fetchpriority="high"', tag)

    def test_tables_bag_audit_link_and_figures(self):
        self.assertIn('<caption class="sr-only">Typical 7-wood carry distance by handicap</caption>', self.html)
        self.assertIn('<caption class="sr-only">Greens in regulation from 175 yards with a hybrid versus a long iron, by handicap</caption>', self.html)
        for cell in ("215&ndash;225 yards", "180&ndash;195 yards", "<td>14%</td><td>8%</td>", "<td>44%</td><td>46%</td>"):
            self.assertIn(cell, self.html, cell)
        self.assertIn('href="/tools-bag-audit"', self.html)
        self.assertTrue((ROOT / "tools-bag-audit.html").exists())
        for value in ("200 million shots", "3.8 million rounds", "38.5 degrees", "46.2%", "43.5%", "Rule 4.1b", "Rule 2.4d"):
            self.assertIn(value, self.html, value)

    def test_schema_has_article_faq_publisher_and_breadcrumb(self):
        graph = nodes(self.html)
        types = {n.get("@type") for n in graph}
        self.assertTrue({"Article", "FAQPage", "Organization", "BreadcrumbList"} <= types, types)
        self.assertNotIn("NewsArticle", types)
        article = next(n for n in graph if n.get("@type") == "Article")
        self.assertEqual(CANONICAL, article["mainEntityOfPage"])
        self.assertEqual("Guides", article["articleSection"])
        self.assertEqual("GolfRaw Editorial", article["author"]["name"])
        self.assertEqual("https://www.golfraw.com#organization", article["publisher"]["@id"])
        crumbs = next(n for n in graph if n.get("@type") == "BreadcrumbList")
        self.assertEqual("https://www.golfraw.com/guides", crumbs["itemListElement"][1]["item"])

    def test_visible_faq_matches_the_faqpage_node(self):
        faq = [n for n in nodes(self.html) if n.get("@type") == "FAQPage"]
        self.assertEqual(1, len(faq))
        schema = [(q["name"], q["acceptedAnswer"]["text"]) for q in faq[0]["mainEntity"]]
        self.assertEqual(4, len(schema))
        self.assertEqual(extract_visible_faq(self.html), schema)
        self.assertEqual("What is the easiest golf club to hit for beginners?", schema[0][0])

    def test_synced_surfaces_carry_the_guide(self):
        for name in ("index.html", "guides.html", "news.html", "search.html", "feed.xml"):
            with self.subTest(name):
                self.assertIn(f"/{SLUG}", (ROOT / name).read_text(encoding="utf-8"))
        sitemap = (ROOT / "sitemap.xml").read_text(encoding="utf-8")
        self.assertIn(f"<loc>{CANONICAL}</loc>\n    <lastmod>2026-09-24</lastmod>", sitemap)
        # a guide, not news: it must stay out of the Google News sitemap
        self.assertNotIn(SLUG, (ROOT / "news-sitemap.xml").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
