"""Explicit SEO title and description overrides for published pages.

The page HTML is generated by several small article and page generators.  The
visible article registry title is also used in cards and feeds, so it is not a
safe source for search metadata: changing it would change visible editorial
labels.  This module is the shared, route-keyed source for the small set of
metadata corrections that need to be applied consistently by every generator.

Only ``<title>`` and description/social mirrors are changed here.  Canonicals,
headings, article content, JSON-LD, images and links deliberately remain byte
for byte unchanged.
"""

from __future__ import annotations

import html
import os
import re
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit


ROOT = Path(__file__).resolve().parents[1]


# These are editorially reviewed values, rather than mechanical truncations.
# They intentionally omit the brand suffix where the complete title already
# carries the page intent; the site brand remains present in site chrome and
# social/site-name metadata.
ARTICLE_SEO_OVERRIDES: dict[str, dict[str, str]] = {
    "/equipment/golf-deals-equipment-tee-times-guide": {
        "title": "Golf Deals: Save $2,176 Annually on Equipment and Rounds",
    },
    "/news-2026-tiger-woods-pleads-guilty-reckless-driving-jupiter-island": {
        "title": "Tiger Woods Pleads Guilty: 5-Year Ban and $1,000 Fine",
    },
    "/news-2026-bmw-championship-round-3-scores-odds-recap": {
        "title": "BMW Championship Round 3: Wyndham Clark Leads by 5",
    },
    "/news-2026-brandt-jobe-ally-challenge-jackson": {
        "title": "Brandt Jobe's Ally Challenge: Best Week in Over a Year",
    },
    "/news-2026-charlotte-womens-golf-begins-season-quail-hollow": {
        "title": "Charlotte Women's Golf Begins 2026 Season at Quail Hollow",
    },
    "/news-2026-end-of-season-driver-deals": {
        "title": "End-of-Season Driver Deals: What's Actually Worth Buying",
    },
    "/news-2026-hovland-on-what-makes-scheffler-successful": {
        "title": "Hovland on What Makes Scheffler Successful, in 8 Words",
    },
    "/news-2026-hovland-one-shot-lead-tour-championship": {
        "title": "Hovland's One-Shot Lead Came From Six Straight Putts",
    },
    "/news-2026-hovland-tour-championship-runner-up": {
        "title": "Hovland's Tour Championship Runner-Up and What He Said",
    },
    "/news-2026-jon-rahm-liv-golf-future": {
        "title": "Jon Rahm LIV Golf Future: August 2026 Update",
    },
    "/news-2026-jon-rahm-liv-money-owed": {
        "title": "Jon Rahm's LIV Money: What He's Owed and Who Gets Paid",
    },
    "/news-2026-justin-thomas-mental-capacity-bay-hill": {
        "title": "Justin Thomas's 'Mental Capacity' Line, Six Months On",
    },
    "/news-2026-kevin-hart-golf-youtube-132": {
        "title": "Kevin Hart Shot 132 on His New Golf YouTube Channel",
    },
    "/news-2026-liv-golf-bankruptcy-chapter-11-explained": {
        "title": "LIV Golf Bankruptcy: What Chapter 11 Would Actually Do",
    },
    "/news-2026-liv-golf-pif-withdrawal-season-end": {
        "title": "LIV Golf Ends 2026 Season Early Following PIF Withdrawal",
    },
    "/news-2026-liv-golf-settlement-offers-bankruptcy": {
        "title": "LIV Golf Settlement Offers: Cents on the Dollar, Explained",
    },
    "/news-2026-lpga-tour-golfer-costs-alexa-pano-expenses": {
        "title": "LPGA Tour Golfer Costs: $250k Earnings Yields $37,620",
    },
    "/news-2026-michael-block-ally-challenge": {
        "title": "Michael Block's Ally Challenge: A 36-Hole Record, Then 74",
    },
    "/news-2026-michael-block-lead-ally-challenge": {
        "title": "Michael Block's 2-Shot Lead at the Ally Challenge Explained",
    },
    "/news-2026-pga-tour-winners-2026": {
        "title": "PGA Tour Winners 2026: 28 Names, 35 Events, One Left",
    },
    "/news-2026-scheffler-ted-scott-finding-the-number": {
        "title": "Scottie Scheffler and Ted Scott: How They Find the Number",
    },
    "/news-2026-scheffler-true-strokes-gained": {
        "title": "Scottie Scheffler's True Strokes Gained: 12th Since 1983",
    },
    "/news-2026-scott-oneil-linkedin-post-liv-golf": {
        "title": "Scott O'Neil's LinkedIn Post on LIV Golf 1.0, Fact-Checked",
    },
    "/news-2026-scottie-scheffler-captures-fedex-cup": {
        "title": "Scottie Scheffler Captures the FedEx Cup and Passes Tiger",
    },
    "/news-2026-scottie-scheffler-final-press-conference-answer": {
        "title": "Scottie Scheffler's Final Press Conference Answers",
        "description": (
            "After winning $10 million and a second FedEx Cup, Scottie Scheffler "
            "passed Tiger Woods on the money list and discussed wind and family travel."
        ),
    },
    "/news-2026-small-grip-change-big-swing-improvement": {
        "title": "Small Grip Change, Big Swing Improvement",
    },
    "/news-2026-the-end-of-liv-golf-bankruptcy": {
        "title": "The End of LIV Golf? What a Bankruptcy Would Really Mean",
    },
    "/news-2026-tiger-woods-career-money-list-record": {
        "title": "Tiger Woods' Career Money List Record May Fall Today",
    },
    "/news-2026-tour-championship-final-round-hovland-leads": {
        "title": "Tour Championship Final Round: Hovland Leads by One",
    },
    "/news-2026-tour-championship-points-and-payouts": {
        "title": "Tour Championship Points and Payouts: All 29 Checks",
    },
    "/news-2026-tour-championship-round-3-tee-times-leaderboard": {
        "title": "Tour Championship Round 3: Hovland's 65 and Every Score",
    },
    "/news-2026-tour-championship-sunday-tee-times-round-4": {
        "title": "2026 Tour Championship Sunday Tee Times: Everything Moved",
    },
    "/news-2026-tour-championship-tee-times-round-4": {
        "title": "2026 Tour Championship Tee Times: Round 4 at East Lake",
    },
    "/news-2026-tour-championship-winners-losers-friday": {
        "title": "Tour Championship Winners & Losers: Scheffler Surges",
    },
    "/news-2026-trump-honorary-chairman-presidents-cup-2026": {
        "title": "Trump Named Honorary Chairman of the Presidents Cup Again",
    },
    "/news-2026-wyndham-clark-gary-woodland-bmw-championship-recap": {
        "title": "Wyndham Clark Leads BMW Championship by 5",
        "description": (
            "Wyndham Clark leads the BMW Championship by five at Bellerive as Gary "
            "Woodland's 199 protects his Tour Championship bubble."
        ),
    },
    "/news-every-shot-tiger-woods-80th-win-2018": {
        "title": "Every Shot From Tiger Woods' 80th Win: What to Watch For",
    },
    "/scottie-scheffler-swing-explained": {
        "title": "Scottie Scheffler's Swing: The Foot Slide Is a Symptom",
    },
    "/strokes-gained": {
        "title": "What Does Strokes Gained Mean? A Simple Golf Explanation",
    },
    "/golf-clubs-for-beginners": {
        "title": "Golf Clubs for Beginners: What You Actually Need",
    },
    "/why-pros-are-ditching-hybrids": {
        "title": "Why Pros Are Ditching Hybrids, and Why You Shouldn't",
    },
    "/guides-how-to-play-in-a-golf-pro-am-costs-etiquette": {
        "title": "How to Play in a Golf Pro-Am: Costs & Etiquette",
    },
    "/news-2026-how-much-pro-am-costs": {
        "title": "How Much Does a Pro-Am Cost? PGA vs Local Events",
    },
}


# The equipment page is also one of the four overlong descriptions found in
# the audit. Keeping the values in the same route-keyed catalog makes it
# impossible for the shared finalizers to update only one social mirror.
ARTICLE_SEO_OVERRIDES["/equipment/golf-deals-equipment-tee-times-guide"]["description"] = (
    "Save $2,176 annually on golf equipment, balls and tee times with data on "
    "release cycles, urethane balls and twilight rates."
)
ARTICLE_SEO_OVERRIDES["/news-2026-donald-trump-amgen-irish-open-doonbeg"] = {
    "description": (
        "President Donald Trump is scheduled to attend the 2026 Amgen Irish Open "
        "at his Doonbeg golf course. The visit brings major security to County Clare."
    ),
}


_ATTR_RE = re.compile(
    r"([:\w-]+)\s*=\s*(?:\"([^\"]*)\"|'([^']*)'|([^\s>]+))", re.S
)
_HEAD_RE = re.compile(r"(<head\b[^>]*>)(.*?)(</head\s*>)", re.I | re.S)
_TITLE_RE = re.compile(r"<title\b[^>]*>.*?</title\s*>", re.I | re.S)
_META_RE = re.compile(r"<meta\b[^>]*>", re.I | re.S)


def _attributes(tag: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for match in _ATTR_RE.finditer(tag):
        value = next(group for group in match.groups()[1:] if group is not None)
        result[match.group(1).lower()] = html.unescape(value)
    return result


def _route_for(path: str | os.PathLike[str]) -> str:
    """Normalize a route, relative HTML path, absolute HTML path, or URL."""
    raw = os.fspath(path)
    if "://" in raw:
        raw = urlsplit(raw).path
    candidate = Path(raw)
    if candidate.is_absolute():
        try:
            raw = candidate.resolve().relative_to(ROOT).as_posix()
        except ValueError:
            # A leading slash is also how a site route is written. Preserve
            # it when it is not an absolute path inside this repository.
            if not raw.startswith("/") or raw.endswith(".html"):
                raw = candidate.name
    raw = raw.replace(os.sep, "/")
    if raw.startswith("./"):
        raw = raw[2:]
    if raw.endswith("/index.html"):
        raw = raw[:-10]
    elif raw == "index.html":
        raw = ""
    elif raw.endswith(".html"):
        raw = raw[:-5]
    route = "/" + raw.lstrip("/")
    if route != "/":
        route = route.rstrip("/")
    return route


def metadata_override_for(path: str | os.PathLike[str]) -> dict[str, str]:
    """Return the reviewed override for a route or an empty mapping."""
    return ARTICLE_SEO_OVERRIDES.get(_route_for(path), {})


def _replace_tag_content(tag: str, value: str) -> str:
    pattern = re.compile(r"(\bcontent\s*=\s*)([\"'])(.*?)(\2)", re.I | re.S)
    updated, count = pattern.subn(
        lambda match: f"{match.group(1)}{match.group(2)}{html.escape(value, quote=True)}{match.group(4)}",
        tag,
        count=1,
    )
    if count != 1:
        raise ValueError("managed meta tag has no quoted content attribute")
    return updated


def _replace_meta_field(head: str, kind: str, field: str, value: str) -> str:
    matches = []
    for match in _META_RE.finditer(head):
        attrs = _attributes(match.group(0))
        identity = (attrs.get(kind) or "").casefold()
        if identity == field.casefold():
            matches.append(match)
    if len(matches) != 1:
        raise ValueError(f"expected one {kind}={field} meta tag, found {len(matches)}")
    match = matches[0]
    replacement = _replace_tag_content(match.group(0), value)
    return head[: match.start()] + replacement + head[match.end() :]


def _replace_title(head: str, value: str) -> str:
    matches = list(_TITLE_RE.finditer(head))
    if len(matches) != 1:
        raise ValueError(f"expected one title tag, found {len(matches)}")
    match = matches[0]
    replacement = f"<title>{html.escape(value)}</title>"
    return head[: match.start()] + replacement + head[match.end() :]


def apply_metadata_overrides(
    source: str, path: str | os.PathLike[str]
) -> str:
    """Apply one route's explicit title/description to all head mirrors."""
    override = metadata_override_for(path)
    if not override:
        return source
    match = _HEAD_RE.search(source)
    if not match:
        raise ValueError("managed metadata override requires a <head> element")

    head = match.group(2)
    if "title" in override:
        head = _replace_title(head, override["title"])
        for kind, field in (("property", "og:title"), ("name", "twitter:title")):
            head = _replace_meta_field(head, kind, field, override["title"])
    if "description" in override:
        head = _replace_meta_field(head, "name", "description", override["description"])
        for kind, field in (("property", "og:description"), ("name", "twitter:description")):
            head = _replace_meta_field(head, kind, field, override["description"])

    return source[: match.start()] + match.group(1) + head + match.group(3) + source[match.end() :]


class _MetadataParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.in_head = 0
        self.title_depth = 0
        self.titles: list[str] = []
        self.meta: dict[str, list[str]] = {}
        self._title_buffer: list[str] = []

    def handle_starttag(self, tag: str, attrs) -> None:  # type: ignore[no-untyped-def]
        tag = tag.casefold()
        values = {str(key).casefold(): value or "" for key, value in attrs}
        if tag == "head":
            self.in_head += 1
        elif tag == "title" and self.in_head:
            self.title_depth += 1
            self._title_buffer = []
        elif tag == "meta" and self.in_head:
            key = (values.get("name") or values.get("property") or "").casefold()
            if key:
                self.meta.setdefault(key, []).append(values.get("content", ""))

    def handle_data(self, data: str) -> None:
        if self.title_depth:
            self._title_buffer.append(data)

    def handle_endtag(self, tag: str) -> None:
        tag = tag.casefold()
        if tag == "title" and self.title_depth:
            self.titles.append("".join(self._title_buffer).strip())
            self.title_depth -= 1
        elif tag == "head":
            self.in_head = max(0, self.in_head - 1)


def audit_metadata(source: str) -> dict[str, object]:
    """Extract the title, description and social mirror counts/values."""
    parser = _MetadataParser()
    parser.feed(source)
    parser.close()
    result: dict[str, object] = {
        "title": parser.titles[0] if parser.titles else "",
        "title_count": len(parser.titles),
    }
    for field in ("description", "og:title", "og:description", "twitter:title", "twitter:description"):
        values = parser.meta.get(field, [])
        result[field] = values[0] if values else ""
        result[f"{field}_count"] = len(values)
    return result
